#################   DATASET CONFIG   ###################

project_name: "PAN_for_CTW1500_640_full"    # also the folder name of the dataset that under ./data folder
data_root: "/home/ubuntu/Documents/working/pixtaVN/RA/TextBPN++/data/CTW1500/yolo"
train_subroot: "chip_for_train"
val_subroot: "chip_for_test"
#################   TRAINING CONFIG   ###################

pretrained: "/home/ubuntu/Documents/working/pixtaVN/RA/PAN.pytorch/TextFocus/weights/PANNet_best_acc.pth"

gpu_devices: '0'                     # supports multi-gpus
num_epochs: 100
batch_size: 1
num_workers: 2

image_size: 320

# learning rate policy
lr_policy:
  name: "adam"                         #[adam|sgd]
  lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
  momentum: 0.937
  weight_decay: 0.0005

lr_scheduler:
  name: "step_lr"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
  step_size: 35
  gamma: 0.1                                   # if need to specify more scheduler arguments, do it here

model:
  backbone: "resnet18"
  fpem_repeat: 2
  pretrained: True
  segmentation_head: "FPEM_FFM"

loss: 
  alpha: 0.5
  beta: 0.25
  delta_agg: 0.5
  delta_dis: 3
  ohem_ratio: 3

using_autofocus: True
autofocus:
  dont_care_low: 3
  dont_care_high: 200
  small_threshold: 50
  stride: 4